// Generated by https://quicktype.io

export interface Categories {
    data: Category[];
    meta: Meta;
}

export interface Category {
    id:         number;
    attributes: CategoryAttributes;
}

export interface CategoryAttributes {
    nombre:      string;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
    productos:   Productos;
    imagen:      Imagen;
}

export interface Imagen {
    data: Data;
}

export interface Data {
    id:         number;
    attributes: DataAttributes;
}

export interface DataAttributes {
    name:              string;
    alternativeText:   null;
    caption:           null;
    width:             number;
    height:            number;
    formats:           Formats;
    hash:              string;
    ext:               string;
    mime:              string;
    size:              number;
    url:               string;
    previewUrl:        null;
    provider:          string;
    provider_metadata: ProviderMetadata;
    createdAt:         string;
    updatedAt:         string;
}

export interface Formats {
    medium:    Large;
    thumbnail: Large;
    small:     Large;
    large:     Large;
}

export interface Large {
    name:              string;
    hash:              string;
    ext:               string;
    mime:              string;
    path:              null;
    width:             number;
    height:            number;
    size:              number;
    url:               string;
    provider_metadata: ProviderMetadata;
}

export interface ProviderMetadata {
    public_id:     string;
    resource_type: ResourceType;
}

export enum ResourceType {
    Image = "image",
}

export interface Productos {
    data: ProductoData[];
}

export interface ProductoData {
    id:         number;
    attributes: ProductAttributes;
}

export interface ProductAttributes {
    nombre:      string;
    descripcion: string;
    disponible:  boolean;
    existencias: number;
    precio:      number;
    createdAt:   string;
    updatedAt:   string;
    publishedAt: string;
}

export interface Meta {
    pagination: Pagination;
}

export interface Pagination {
    page:      number;
    pageSize:  number;
    pageCount: number;
    total:     number;
}
